### ISSUE TITLE
Описать README

### ISSUE THREAD

**Issue by fedotarte** [Smelch228/icis-pp-events#1]
Андрюх, отбранчуйся в новую ветку(dev), опиши,  че за проект в маркдауне в README.md(можно превьюшный плагин на IDE поставить), открой пул-реквест(из dev в main), но не смерживай.
Если ниче не выйдет, или затруднения будут - пиши

**Comment by Smelch228** [comment]
сделано, можешь чекнуть

**Comment by fedotarte** [comment]
Добавь как запуск проекта делать

**Comment by Smelch228** [comment]
readme fixed
